import Head from "next/head";
import Expert from "../components/About/Expert";
import Layout from "../components/Layout";

const About = () => {
  return (
    <div>
      <Head>
        <title>Neuronious</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <Layout>
        <Expert />
      </Layout>
    </div>
  );
};

export default About;
